### ISSUE TITLE
Require login for uploaded files

### ISSUE THREAD

**Issue by lyatziv** [suiteplus/nscabinet#1]
After uploading files the platform requires a login to access. Is this a provisioning setting or is there something that can be done in the config?

**Comment by wkrueger** [comment]
Hello,
It expects at least `email`, `password`, `account` and `script` (restlet id as number).

The suggested way of setting this is creating a `nsconfig.json` file at the root of your project. You may also pass them as an object.

**Comment by lyatziv** [comment]
Indeed. All the necessary parameters are being passed. The files are being
uploaded to the appropriate destination that has web accessible assets. The
issue is that files either updated or newly created, require login where
the original file didn't.
