### ISSUE TITLE
Restlet is crashing when files are not found

### ISSUE THREAD

**Issue by timaschew** [suiteplus/nscabinet#13]
Why not just ignore files which cannot be found on NetSuite, at least what about to configure this behaviour?

**Comment by wkrueger** [comment]
got it, if one of the queried files is not found, the whole process is aborted and the other files are not sent.

Would have to send the errors back in a "warnings object" and show them to the user.
Also, make that warnings object acessible for gulp users.

**Comment by timaschew** [comment]
sounds good :+1: 

---

Another thing I found that if using a wildcard like `src/*`
The search result contains all files, even recursive, but there is a filter function which pass only children of `src`. Why not return all results, even recursive to the user?

Here is the line:
https://github.com/suiteplus/nscabinet/blob/3596033cd99732b0b8a5e39f339f88b76d549151/restlet/nscabinet-restlet.js#L89

**Comment by wkrueger** [comment]
The user won't always want the recursive results.
Following the glob pattern, if I ask for `src/*js` I just want the files inside src.
Would have to implement something mimicking the `src/**/*.js` pattern for recursive results.

**Comment by timaschew** [comment]
Yes, the pattern would be `src/**/*.js`
I did try to achieve this, but I didn't managed this, because it looks like I need to fetch for each parent id the folder name and track the hierarchy.
Or is there an NetSuite API call to fetch all folder names recursively?

**Comment by wkrueger** [comment]
whoops, recursive and forgiving search are available since 0.5.0!
