### ISSUE TITLE
Blocking error

### ISSUE THREAD

**Issue by laviyatziv** [suiteplus/nscabinet#19]
Was using this script without issue, OSX did an update to 10.11.5 and now it's kaput.

`USER_ERROR - Could not determine customer compid`

I don't think there is a parameter in the config to set `compid`; Also, unsure of where to find that ID

Thanks!

**Comment by laviyatziv** [comment]
Disregard issue: The error was a result of an expired password.

**Comment by wkrueger** [comment]
Yeah netsuite often "encodes" its error messages :(

2016-06-07 12:39 GMT-03:00 Lavi Yatziv notifications@github.com:
