### ISSUE TITLE
When trying to upload a file I get "SSS_INVALID_SCRIPTLET_ID"

### ISSUE THREAD

**Issue by vicdidia** [suiteplus/nscabinet#22]
When I try the sample code I get an error that says "SSS_INVALID_SCRIPTLET_ID - That Suitelet is invalid, disabled, or no longer exists."

I have uploaded the restlet and I have filled out the config option directly in the script instead of a config file.

When I set the realm as 'system.na1.netsuite.com' I get the error

`events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND rest.system.na1.netsuite.com rest.system.na1.netsuite.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:76:26)`

**Comment by vicdidia** [comment]
Just an update, on a different machine I tried it again and got the error:

```
node_modules/nscabinet/src/nscabinet.js:51
        request( toRequest ).on('response', response => {
                                                      ^
SyntaxError: Unexpected token >
```

Any ideas on why this happens?

**Comment by danieljoppi** [comment]
what is your node version?

**Comment by vicdidia** [comment]
I have version 6.7.0 on Mac. My second machine is Ubuntu and it's running version 4.2.6.

Also on that second machine, I now get the error `SSS_INVALID_SCRIPTLET_ID - That Suitelet is invalid, disabled, or no longer exists.` So now both machines have the same error.

**Comment by vicdidia** [comment]
I tried again and now it says `Uploading File.json to /SuiteScripts` which it hasn't said in a while. Unfortunately, still same error.

**Comment by vicdidia** [comment]
I have solved this problem. The problem was that I wasn't setting the scriplet ID from Netsuite as the script parameter.
