### ISSUE TITLE
ENOTFOUND

### ISSUE THREAD

**Issue by edulis8** [suiteplus/nscabinet#23]
Any tips:?
After gulp upload I get:

  throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND rest.rest.na2.netsuite.com rest.rest.na2.netsuite.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:76:26)

**Comment by mattgaspar** [comment]
Try changing the realm you have setup to na2.netsuite.com
Don't include rest, the script automatically adds that part.

**Comment by wkrueger** [comment]
Mostly that!
