### ISSUE TITLE
Doesn't Work with New NetSuite URLs

### ISSUE THREAD

**Issue by NZaleski** [suiteplus/nscabinet#29]
Our URL is now in this format
https://[account].app.netsuite.com

Where account is either just the account number for production, or account number + '-SB1' fort sandbox. 

This currently does not work

**Comment by mattgaspar** [comment]
Version 0.7.0 is now updated to use account specific domains.

Install from Github using `npm install suiteplus/nscabinet` (the version on npm is outdated and I don't have access to publish there)

**Comment by NZaleski** [comment]
Oh okay thanks!
