### ISSUE TITLE
default realm is not working

### ISSUE THREAD

**Issue by timaschew** [suiteplus/nscabinet#4]
If you don't set the realm, I get this error by the CLI

`Error: getaddrinfo ENOTFOUND rest.system.netsuite.com rest.system.netsuite.com:443`

**Comment by wkrueger** [comment]
Oops.
A version from nsconfig (0.3.1) was missing on npm. Shall be up in a couple minutes.
https://github.com/suiteplus/nsconfig/commit/cd169a9863f987337a6279c712eb337d0f553029
