### ISSUE TITLE
Make the upload restlet available in a suitebundle

### ISSUE THREAD

**Issue by wkrueger** [suiteplus/nscabinet#9]
For setup convenience.

**Comment by wkrueger** [comment]
Restlet available publicly as nscabinet bundle.
Bundle version will always match the "client-side" counterpart version.

**Comment by timaschew** [comment]
Can you explain how you published it?

**Comment by timaschew** [comment]
Friendly ping :point_right: 
Just wanted to know if you did it by hand on the NetSuite webinterface or via an API?

**Comment by danieljoppi** [comment]
Install via Bundle: https://system.na1.netsuite.com/app/bundler/installbundle.nl
Name: `nscabinet restlet`
ID: `108382`
Company: `TSTDRV521633`

**Comment by timaschew** [comment]
No ^^ I want to know how to publish a bundle, not how to install it.

And the main question is if this publishing process can be automated via an API or is it only possible to do this by hand with the Webinterface of NetSuite and the BundleBuilder.

I think this is the part of **Deploy** of https://github.com/suiteplus/gulp-nstools#deploy
